# Generated by Django 3.1.1 on 2020-09-25 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 20, 5, 48, 429827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 20, 5, 48, 430825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_photo',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='', width_field=600),
        ),
    ]
