# Generated by Django 3.1.3 on 2020-11-15 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201008_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviw',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 7, 46, 52, 975825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 7, 46, 52, 978821, tzinfo=utc)),
        ),
    ]
